name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.39.99.70 <<EOF
            PROCESS_NAME="GoWash-back-reservations"
            cd /var/www/goWash/\$PROCESS_NAME || exit 1
            git pull origin main
            npm install
            npm run build

             PROCESS_NAME=\$PROCESS_NAME
            if pm2 list | grep -q \$PROCESS_NAME; then
              pm2 stop \$PROCESS_NAME
            else
              echo 'Process \$PROCESS_NAME not found, skipping stop.'
            fi
            pm2 start dist/main.js --name '\$PROCESS_NAME'
          EOF
